### PR TITLE
fragmenter: add dynamic memory management for internal conn-allocation

### PR DESCRIPTION
**Pull request by miri64**
Required for my [python wrapper](https://github.com/anr-bmbf-pivot/pylibschc).

### CODE REVIEW

**Comment by bartmoons** [comment]
I get a segmentation fault when running the `fragment` example with `DYNAMIC_MEMORY 1`.

**Comment by bartmoons** [comment]
Stacktrace:
```
Thread 1 "fragment" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x000055555555d905 in schc_reassemble (rx_conn=0x5555555787d0)
    at ../fragmenter.c:1519
#2  0x0000555555557b15 in received_packet (
    data=0x555555577460 <FRAGMENTATION_BUF> "\002", length=121, device_id=1, 
    receiving_conn=0x555555577280 <tx_conn_nwgw>) at fragment.c:259
#3  0x0000555555557b93 in tx_send_callback (
    data=0x555555577460 <FRAGMENTATION_BUF> "\002", length=121, device_id=1)
    at fragment.c:276
#4  0x000055555555cdc1 in send_fragment (conn=0x5555555771e0 <tx_conn>)
    at ../fragmenter.c:1186
#5  0x000055555555f026 in schc_fragment (tx_conn=0x5555555771e0 <tx_conn>)
    at ../fragmenter.c:2152
#6  0x000055555555ec02 in schc_fragment (tx_conn=0x5555555771e0 <tx_conn>)
    at ../fragmenter.c:2039
#7  0x0000555555557db9 in main () at fragment.c:342
```

**Comment by miri64** [comment]
Fixed, but it required an API change and also moving the initialization of the new conn object from `schc_fragmenter_init()` to after `schc_connection_get()` (which IMHO makes also more sense, as `schc_fragmenter_init()` initializes the `tx`).

**Comment by bartmoons** [comment]
Thanks, looks good!

**Pull request merged**
